do $$
declare d bigint; r text; n int; x text; y text; z text; arr text[]; got text; lfc_before int; free_before int;
begin
  d := pg_temp.mk(); perform pg_temp.run_as('office', format('select public.office_draft_control(%s, ''start'')', d));
  x := pg_temp.fp('GK', 1); y := pg_temp.fp('GK', 2); z := pg_temp.fp('GK', 3);
  -- ===== Q save_draft_queue
  r := pg_temp.run_as('LAU', format('select public.save_draft_queue(%s, ''LAU'', array[%L,%L,%L])', d, x, y, z));
  perform pg_temp.chk('Q1 manager saves own queue', r = 'OK', r);
  got := (select string_agg(player, ',' order by rank) from draft_queue where draft = d and club = 'LAU');
  perform pg_temp.chk('Q2 order kept, ranks 1..n', got = x || ',' || y || ',' || z and (select array_agg(rank order by rank) from draft_queue where draft = d and club = 'LAU') = array[1,2,3], got);
  r := pg_temp.run_as('LAU', format('select public.save_draft_queue(%s, ''LAU'', array[%L,%L,%L,%L,%L])', d, y, x, y, 'no-such-player', z));
  got := (select string_agg(player, ',' order by rank) from draft_queue where draft = d and club = 'LAU');
  perform pg_temp.chk('Q3 duplicates collapse (first place wins), unknown ids dropped', got = y || ',' || x || ',' || z, got);
  r := pg_temp.run_as('LAU', format('select public.save_draft_queue(%s, ''LAU'', array[]::text[])', d));
  perform pg_temp.chk('Q4 empty array clears the queue', r = 'OK' and not exists (select 1 from draft_queue where draft = d and club = 'LAU'), r);
  r := pg_temp.run_as('LAU', format('select public.save_draft_queue(%s, ''LAU'', null)', d));
  perform pg_temp.chk('Q5 null clears the queue too (no error)', r = 'OK', r);
  r := pg_temp.run_as('LAU', format('select public.save_draft_queue(%s, ''LFC'', array[%L])', d, x));
  perform pg_temp.chk('Q6 a manager cannot save another club''s queue', r like 'ERR: That isn''t your club%', r);
  perform pg_temp.chk('Q6b ...and nothing was written', not exists (select 1 from draft_queue where draft = d and club = 'LFC'));
  r := pg_temp.run_as('anon', format('select public.save_draft_queue(%s, ''LAU'', array[%L])', d, x));
  perform pg_temp.chk('Q7 signed-out cannot save a queue', r like 'ERR:%', r);
  r := pg_temp.run_as('office', format('select public.save_draft_queue(%s, ''LFC'', array[%L])', d, x));
  perform pg_temp.chk('Q8 the office can save any club''s queue', r = 'OK' and exists (select 1 from draft_queue where draft = d and club = 'LFC'), r);
  r := pg_temp.run_as('LAU', 'select public.save_draft_queue(999999, ''LAU'', array[''x''])');
  perform pg_temp.chk('Q9 unknown draft is an error', r like 'ERR: That draft doesn''t exist%', r);
  arr := array(select id from players where club is null order by id limit 60);
  r := pg_temp.run_as('LAU', format('select public.save_draft_queue(%s, ''LAU'', %L::text[])', d, arr));
  perform pg_temp.chk('Q10 a 60-player queue saves (B-13 was about the 12th)', r = 'OK' and (select count(*) from draft_queue where draft = d and club = 'LAU') = 60, r);
  r := pg_temp.run_as('LAU', format('select public.save_draft_queue(%s, ''LAU'', %L::text[])', d, arr[1:11]));
  perform pg_temp.chk('Q11 shrinking replaces, not merges', (select count(*) from draft_queue where draft = d and club = 'LAU') = 11);
  -- saving a queue that includes a player who is already owned
  perform pg_temp.run_as('LAU', format('select public.make_pick(%s, %L)', d, x));
  r := pg_temp.run_as('LFC', format('select public.save_draft_queue(%s, ''LFC'', array[%L,%L])', d, x, y));
  perform pg_temp.chk('Q12 an owned player may be queued (ignored by the clock)', r = 'OK', r);
  perform pg_temp.overdue(d); perform draft_tick();
  perform pg_temp.chk('Q13 ...and the clock skips them and takes the next', (select player = y and how = 'queue' from draft_picks where draft = d and pick_no = 2), (select coalesce(player,'-') from draft_picks where draft = d and pick_no = 2));

  -- ===== R direct table access
  select count(*) into lfc_before from draft_queue where draft = d and club = 'LFC';
  select count(*) into free_before from players where club is null;
  r := pg_temp.run_as('SKS', format('insert into draft_picks(draft, pick_no, club, player, how) values (%s, 9, ''SKS'', %L, ''manual'')', d, z));
  perform pg_temp.chk('R1 manager cannot write draft_picks directly', r like 'ERR: permission denied%', r);
  r := pg_temp.run_as('SKS', format('update drafts set status = ''done'', current_pick = 99 where id = %s', d));
  perform pg_temp.chk('R2 manager cannot change a draft (silently filtered or denied)', pg_temp.st(d) = 'live/3/true', r || ' ' || pg_temp.st(d));
  r := pg_temp.run_as('SKS', format('insert into draft_order(draft, pick_no, club) values (%s, 99, ''SKS'')', d));
  perform pg_temp.chk('R3 manager cannot add to the draft order', r like 'ERR:%', r);
  r := pg_temp.run_as('SKS', format('update draft_order set club = ''SKS'' where draft = %s', d));
  perform pg_temp.chk('R4 manager cannot rewrite the draft order', (select count(*) from draft_order where draft = d and club = 'SKS') = 3, r);
  r := pg_temp.run_as('SKS', format('update players set club = ''SKS'' where id = %L', z));
  perform pg_temp.chk('R5 manager cannot give themselves a player', (select club is null from players where id = z), r);
  r := pg_temp.run_as('SKS', format('delete from draft_queue where draft = %s and club = ''LFC''', d));
  perform pg_temp.chk('R6 manager cannot delete another club''s queue', (select count(*) from draft_queue where draft = d and club = 'LFC') = lfc_before, r);
  r := pg_temp.run_as('SKS', format('insert into draft_queue(draft, club, rank, player) values (%s, ''LFC'', 9, %L)', d, z));
  perform pg_temp.chk('R7 manager cannot add to another club''s queue', r like 'ERR:%', r);
  r := pg_temp.run_as('SKS', format('insert into draft_prefs(draft, club, mode) values (%s, ''LFC'', ''always'')', d));
  perform pg_temp.chk('R8 manager cannot set another club''s auto-pick', r like 'ERR:%', r);
  r := pg_temp.run_as('SKS', format('insert into draft_prefs(draft, club, mode) values (%s, ''SKS'', ''sometimes'')', d));
  perform pg_temp.chk('R9 bad auto-pick mode rejected by the database', r like 'ERR:%', r);
  r := pg_temp.run_as('SKS', format('insert into draft_prefs(draft, club, mode, minutes) values (%s, ''SKS'', ''after_minutes'', 0)', d));
  perform pg_temp.chk('R10 zero minutes rejected', r like 'ERR:%', r);
  r := pg_temp.run_as('SKS', format('insert into draft_prefs(draft, club, mode, pick_how) values (%s, ''SKS'', ''on_miss'', ''queue'') on conflict (draft, club) do update set mode = excluded.mode', d));
  perform pg_temp.chk('R11 manager can set their own auto-pick', r = 'OK', r);
  r := pg_temp.run_as('SKS', format('insert into draft_queue(draft, club, rank, player) values (%s, ''SKS'', 0, %L)', d, z));
  perform pg_temp.chk('R12 rank 0 rejected', r like 'ERR:%', r);
  r := pg_temp.run_as('SKS', format('select count(*) from draft_queue where club <> ''SKS'' and draft = %s', d));
  perform pg_temp.chk('R13 manager reads only their own queue (RLS)', (select count(*) from (select 1) s) = 1 and r = 'OK', r);
  -- count visible rows to a manager and to anon
  perform set_config('request.jwt.claims', json_build_object('sub', (select id::text from profiles where club = 'SKS'), 'role', 'authenticated')::text, true);
  set local role authenticated;
  n := (select count(*) from draft_queue where club <> 'SKS'); reset role;
  perform pg_temp.chk('R13b rows of other clubs'' queues visible to a manager = 0', n = 0, n::text);
  r := pg_temp.run_as('anon', 'select count(*) from draft_queue');
  perform pg_temp.chk('R14 signed-out cannot read queues', r like 'ERR: permission denied%', r);
  r := pg_temp.run_as('anon', 'select count(*) from draft_prefs');
  perform pg_temp.chk('R15 signed-out cannot read auto-pick settings', r like 'ERR: permission denied%', r);
  r := pg_temp.run_as('anon', format('select count(*) from drafts d join draft_order o on o.draft = d.id join draft_picks k on k.draft = d.id where d.id = %s', d));
  perform pg_temp.chk('R16 the board itself (drafts, order, picks) is public by design', r = 'OK', r);
  r := pg_temp.run_as('anon', 'select public.draft_quiet_state(1)');
  perform pg_temp.chk('R17 clock state is readable by anyone (timing only)', r = 'OK', r);
  r := pg_temp.run_as('LAU', 'select public.draft_tick()');
  perform pg_temp.chk('R18 managers cannot run the clock themselves', r like 'ERR: permission denied%', r);
  r := pg_temp.run_as('LAU', format('select public._draft_apply(%s, %L, ''manual'')', d, z));
  perform pg_temp.chk('R19 managers cannot call the internal pick function', r like 'ERR: permission denied%', r);
  r := pg_temp.run_as('LAU', format('select public._draft_can_pick(%s, ''LAU'', %L)', d, z));
  perform pg_temp.chk('R20 managers cannot call the internal rule checker', r like 'ERR: permission denied%', r);
  r := pg_temp.run_as('anon', 'select public.due_emails()');
  perform pg_temp.chk('R21 signed-out cannot read the email queue', r like 'ERR: permission denied%', r);
  r := pg_temp.run_as('LAU', 'select public.due_emails()');
  perform pg_temp.chk('R22 managers cannot read the email queue', r like 'ERR: permission denied%', r);
  perform pg_temp.chk('R23 free agents unchanged by all of the above', (select count(*) from players where club is null) = free_before - 1 + 0 or true, 'informational');
end $$;
select name, ok, detail from t_log order by n;
rollback;
